F1Network/Models/Car.cs
namespace F1Network.Models
{
    public class Car
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public string PictureURL { get; set; }
        public string Description { get; set; }
        public List<Driver> Drivers { get; set; }
        public int ManufacturerId { get; set; }
        public Manufacturer Manufacturer { get; set; }
    }
}

F1Network/Models/Driver.cs
namespace F1Network.Models
{
    public class Driver
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string PictureURL { get; set; }
        public string Description { get; set; }
        
        //Relations
        public int CarId { get; set; }
        public Car Car { get; set; }
        public int ManufacturerId { get; set; }
        public Manufacturer Manufacturer { get; set; }
    }
}

F1Network/Models/Manufacturer.cs
namespace F1Network.Models
{
    public class Manufacturer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PictureURL { get; set; }
        public string Description { get; set; }
        //relations
        public List<Driver> Drivers { get; set; }
        public List<Car> Cars { get; set; }
    }
}

F1Network/Controllers/CarsController.cs
using F1Network.Data.Services;
using Microsoft.AspNetCore.Mvc;

namespace F1Network.Controllers
{
    public class CarsController : Controller
    {
        private readonly ICarsService _service;
        public CarsController(ICarsService service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
            var carsData = _service.GetAll();
            return View(carsData);
        }
    }
}

F1Network/Controllers/HomeController.cs
using F1Network.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace F1Network.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

F1Network/Views/Cars/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

F1Network/Views/Cars/Index.cshtml
@model IEnumerable<Car>

@{
    ViewData["Title"] = "Car List";
}
<h1>List of Cars in season 2022</h1>
<div class="row">
    <div class="col-md-8" style="width:100%;">
        <table class="table">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Manufacturer)</th>
                    <th>@Html.DisplayNameFor(model => model.Model)</th>
                    <th>@Html.DisplayNameFor(model => model.Description)</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="img-fluid" src="@item.PictureURL" alt="@item.Model" style="max-width:200px;"/>
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(model => item.Model)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(model => item.Description)
                        </td>
                        <td class="align-middle" style="width:300px;">
                            <a class="btn btn-outline-primary d-inline-block" asp-action="Edit" asp-route-id="@item.Id">Edit </a> |   
                            <a class="btn btn-outline-info d-inline-block" asp-action="Details" asp-route-id="@item.Id">Details </a> |   
                            <a class="btn btn-outline-danger d-inline-block" asp-action="Delete" asp-route-id="@item.Id">Delete </a>   
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="text-white" style="right:25px; bottom:25px;">
        <a asp-controller="Cars" asp-action="Create" class="btn btn-succes">Create</a>
    </div>
</div>

F1Network/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

F1Network/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - F1Network</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/F1Network.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">F1Network</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - F1Network - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>